/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-31-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   05-29-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
 * 
 * Developers should use this branch for making the changes
 * 
 * Version              Date            Name                Description
 * =========================================================================
 * 1                31-May-2021     Sanket Maindiratta      Add Method implemented
**/
public with sharing class Calculator 
{
    public int (int a, int b)
    {
        
    }
}
